AWSTemplateFormatVersion: 2010-09-09

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-024e6efaf93d85776
      KeyName: Ero
      InstanceType: t2.micro
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: "gp3"
            DeleteOnTermination: "true"
            VolumeSize: "10"
      